import { Metadata } from 'next';
import Navigation from './components/navigation';

export const metadata: Metadata = {
  // title: 'Home | Next Movies',
  title: {
    template: '%s | Next Movies',
    default: 'loading...',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
